name: Training Pipeline (Daily)

on:
  schedule:
    - cron: '0 0 * * *'   # Daily at midnight UTC
  workflow_dispatch:

jobs:
  training-pipeline:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # give more time for upload

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install hopsworks[python]==4.2.*
          # Add python-dotenv here!
          pip install pandas numpy scikit-learn tensorflow joblib pyarrow python-dotenv

      - name: Run Training Pipeline
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: |
          cd training_pipeline
          python train_model.py
